#!/usr/bin/env python3
"""Validate that a repo's docs are usable for doc-aware planning.

Mirrors the docs skill's `validate` workflow mechanical checks (Steps 3a and 3b)
using the vendored scope.py glob engine, with two spec-skill additions:

- Docs marked `exclude: true` in frontmatter are UNMANAGED: they are skipped
  entirely — no glob-validity check, and they are neither counted as owners for
  coverage nor toward the structure requirement. This is how a repo opts a doc
  out of the doc-aware model (scratch/notes/autogenerated docs).
- Coverage gaps are NON-blocking: a repo whose docs exist but do not cover every
  component is "incomplete but usable" per doc-aware Rule 5 — the flow proceeds
  and flags the gaps as boundary callouts. Dead globs and missing structure are
  blocking (exit 1), which is what "valid docs" means for planning.

Checks:
- STRUCTURE (blocking): docs/ must exist with at least one non-excluded doc that
  is either the architecture index (`docs/architecture/index.md`, `index: true`)
  or declares a public API/interface (the docs skill's `[public-api]` marker or
  a `## Public API` / `## Public Interface` heading).
- GLOB VALIDITY — docs validate Step 3a (blocking): every non-excluded,
  non-index doc's globs must each match at least one real repo path. A glob
  matching nothing is a dead ownership claim (the path moved, was deleted, or
  the glob is wrong).
- COMPREHENSIVENESS — docs validate Step 3b (non-blocking): every component
  discovered from the code (package.json with a `name`, Terraform module dirs,
  API route groups) should be owned by some non-excluded, non-index doc's globs.

Usage:
    python3 scripts/validate_docs.py --root . --docs docs
    python3 scripts/validate_docs.py

Exit 0 when valid (or only coverage gaps exist); exit 1 when invalid. Stdlib
only — no third-party dependencies.
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPT_DIR))
from scope import glob_matches_path  # noqa: E402

INDEX_DOC = "docs/architecture/index.md"
API_MARKERS = ("[public-api]", "## Public API", "## Public Interface")


def collect_paths(root: Path) -> set[str]:
    """All tracked repo file paths under root (repo-relative)."""
    proc = subprocess.run(
        ["git", "ls-files"], cwd=str(root), capture_output=True, text=True
    )
    if proc.returncode == 0:
        return {p for p in proc.stdout.splitlines() if p}
    return {
        str(p.relative_to(root))
        for p in root.rglob("*")
        if p.is_file() and not any(part.startswith(".") for part in p.relative_to(root).parts)
    }


def parse_frontmatter(text: str) -> dict:
    """Extract {globs, index, exclude} from a doc's leading --- frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fm = {}
    i = 1
    while i < len(lines):
        if lines[i].strip() == "---":
            break
        line = lines[i]
        if ":" not in line:
            i += 1
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if key == "globs":
            if val:
                try:
                    parsed = ast.literal_eval(val)
                    if isinstance(parsed, list):
                        fm["globs"] = [str(g) for g in parsed]
                except (ValueError, SyntaxError):
                    fm["globs"] = []
            else:
                block = []
                j = i + 1
                while j < len(lines) and lines[j].lstrip().startswith("- "):
                    block.append(lines[j].split("-", 1)[1].strip().strip('"').strip("'"))
                    j += 1
                fm["globs"] = block
                i = j - 1
        elif key in ("index", "exclude"):
            fm[key] = val.lower() == "true"
        i += 1
    return fm


def declares_api(doc: Path) -> bool:
    """True when the doc declares a public API/interface section (docs skill [public-api])."""
    try:
        text = doc.read_text(errors="replace")
    except OSError:
        return False
    return any(marker in text for marker in API_MARKERS)


def discover_components(root: Path) -> list[dict]:
    """Discover code components (mirrors docs validate Step 1)."""
    comps: list[dict] = []
    seen: set[str] = set()

    def add(name, path, kind):
        if path and path not in seen:
            seen.add(path)
            comps.append({"name": name, "path": path, "type": kind})

    for pkg in root.rglob("package.json"):
        rel = pkg.relative_to(root)
        if any(part in ("node_modules",) or part.startswith(".") for part in rel.parts):
            continue
        try:
            data = json.loads(pkg.read_text(errors="replace"))
        except (OSError, json.JSONDecodeError):
            continue
        if data.get("name"):
            add(data["name"], str(pkg.parent.relative_to(root)), "application")

    for mod in root.rglob("modules"):
        if not mod.is_dir():
            continue
        for sub in sorted(mod.iterdir()):
            if sub.is_dir():
                add(sub.name, str(sub.relative_to(root)), "terraform")

    for srv in root.rglob("+server.ts"):
        rel = srv.parent.relative_to(root)
        srel = str(rel)
        if "routes/api" in srel:
            add(srel, srel, "api")

    return comps


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    ap.add_argument("--docs", default=None, help="docs dir (default: <root>/docs)")
    args = ap.parse_args()

    root = Path(args.root)
    docs_dir = Path(args.docs) if args.docs else root / "docs"

    all_paths = collect_paths(root)
    blocking: list[str] = []
    warnings: list[str] = []

    docs = sorted(docs_dir.rglob("*.md")) if docs_dir.is_dir() else []
    if not docs:
        blocking.append("no markdown docs found under docs/ (or docs/ does not exist)")
    if not all_paths:
        warnings.append(f"no tracked repo files found under --root {root}")

    active = []
    for doc in docs:
        fm = parse_frontmatter(doc.read_text(errors="replace"))
        if fm.get("exclude"):
            continue  # unmanaged — opt out of the doc-aware model entirely
        active.append({"doc": doc, "rel": str(doc.relative_to(root)), "fm": fm})

    if not active:
        blocking.append("every doc under docs/ is marked `exclude: true` — no managed docs remain")

    # STRUCTURE: architecture index or a doc declaring a public API
    if active:
        has_index = any(p["rel"] == INDEX_DOC or p["fm"].get("index") for p in active)
        has_api = any(declares_api(p["doc"]) for p in active)
        if not (has_index or has_api):
            blocking.append(
                f"no architecture index ({INDEX_DOC}) and no managed doc declares a public API/interface"
            )

    # GLOB VALIDITY (docs validate 3a) — blocking
    for p in active:
        if p["fm"].get("index"):
            continue  # index docs own `**` by design
        for g in p["fm"].get("globs") or []:
            if not any(glob_matches_path(g, path) for path in all_paths):
                blocking.append(
                    f"GLOB  {p['rel']}: glob {g!r} matches no paths in the repo (stale or wrong)"
                )

    # COMPREHENSIVENESS (docs validate 3b) — non-blocking
    owners = [
        p for p in active
        if not p["fm"].get("index") and (p["fm"].get("globs") or [])
    ]
    for comp in discover_components(root):
        owned = any(
            any(glob_matches_path(g, comp["path"]) for g in o["fm"]["globs"])
            for o in owners
        )
        if not owned:
            warnings.append(
                f"COVERAGE  Component {comp['name']} ({comp['path']}, {comp['type']}) has no owning doc"
            )

    for line in blocking + warnings:
        print(line)
    summary = f"{len(blocking)} blocking, {len(warnings)} coverage warning(s) across {len(docs)} docs"
    print(summary)
    return 1 if blocking else 0


if __name__ == "__main__":
    raise SystemExit(main())
